### ISSUE TITLE
Console spam from embed error in events cog

### ISSUE THREAD

**Issue by i1470s** [i1470s/IVRY-Discord-Bot#10]
Working on this
UnboundLocalError: local variable 'embed' referenced before assignment
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/home/brayden/Desktop/IVRYBot/cogs/events.py", line 72, in on_message
    embed.set_author(name="IVRY Info", icon_url=self.client.user.avatar_url)
UnboundLocalError: local variable 'embed' referenced before assignment

**Comment by i1470s** [comment]
[](url)
